elehr <- tribble(~Variable,~Legend,~Color,
                   'Fin_Ene_Ele','demand','#003C67FF',
                  'Sec_Ene_Ele_Sto_Cha_Gro_LiB','battery charge','#23e893',
                   'Sec_Ene_Ele_Sto_Cha_Gro_PHS','PHS charge','#9afcc9',
                   'Sec_Ene_Ele_Nuc','nuclear','#FF9626FF',
                   'Sec_Ene_Ele_Hyd','hydro','#29dde3FF',
                   'Sec_Ene_Ele_Geo','geothermal','#B74F3AFF',
                   'Sec_Ene_Ele_Coa_wo_CCS','coal w/o CCS','#4A4F54FF',
                   'Sec_Ene_Ele_Coa_w_CCS','coal w/ CCS','#8A9197FF',
                  'Sec_Ene_Ele_Bio_wo_CCS','biomass w/o CCS','#617f00FF',
                  'Sec_Ene_Ele_Bio_w_CCS','biomass w/ CCS','#a7bf5eFF',
                   'Sec_Ene_Ele_Gas_wo_CCS','gas w/o CCS','#8c845b',
                   'Sec_Ene_Ele_Gas_w_CCS','gas w/ CCS','#c2ac69FF',
                   'Sec_Ene_Ele_Oil','oil w/o CCS','#8C655DFF',
                   'Sec_Ene_Ele_Sto_Dis_LiB','battery discharge','#23e893',
                   'Sec_Ene_Ele_Sto_Dis_PHS','PHS discharge','#9afcc9',
                   'Sec_Ene_Ele_Own_Use_Ene_Sup_Hyd','electrolysis','orchid',
                   'Sec_Ene_Ele_Cur','curtailment','#F6CCFFFF',
                   'Sec_Ene_Ele_inc_Cur_Win_Off','offshore wind','#699bffFF',
                   'Sec_Ene_Ele_inc_Cur_Win_Ons','onshore wind','#145db8',
                   'Sec_Ene_Ele_inc_Cur_Solar_Dec','solar rooftop','#FFEE75FF',
                   'Sec_Ene_Ele_inc_Cur_Solar_Cen','solar utility','#FEC906FF',
                   'Sec_Ene_Ele_H2_FC','fuel cell','orchid',
                   'Sec_Ene_Ele_H2_GT','hydrogen gas turbine','orchid',
                   'Trd_Sec_Ene_Ele','trade','#a3e0ffFF')
flag_elehr <- c('Fin_Ene_Ele','Sec_Ene_Ele_Sto_Cha_Gro_PHS','Sec_Ene_Ele_Sto_Cha_Gro_LiB','Sec_Ene_Ele_Own_Use_Ene_Sup_Hyd','Sec_Ene_Ele_Cur')
 
elehr2 <- tribble(~Variable,~Legend,~Color,
                   'Fin_Ene_Ele','demand','#003C67FF',
                   'Sec_Ene_Ele_Sto_Cha_Gro_LiB','battery charge','#23e893',
                   'Sec_Ene_Ele_Sto_Cha_Gro_PHS','PHS charge','#9afcc9',
                   'Sec_Ene_Ele_Nuc','nuclear','#FF9626FF',
                   'Sec_Ene_Ele_Hyd','hydro','#29dde3FF',
                   'Sec_Ene_Ele_Geo','geothermal','#B74F3AFF',
                   'Sec_Ene_Ele_Coa','coal','#4A4F54FF',
                   'Sec_Ene_Ele_Bio','biomass','#AFDD66FF',
                   'Sec_Ene_Ele_Gas','natural gas','#A99F6DFF',
                   'Sec_Ene_Ele_Oil','oil','#8C655DFF',
                   'Sec_Ene_Ele_Sto_Dis_LiB','battery storage','#23e893',
                   'Sec_Ene_Ele_Sto_Dis_PHS','pumped hydro storage','#9afcc9',
                   'Sec_Ene_Ele_Own_Use_Ene_Sup_Hyd','electrolysis','orchid',
                   'Sec_Ene_Ele_Cur','curtailment','#F6CCFFFF',
                   'Sec_Ene_Ele_inc_Cur_Win','wind','#145db8',
                   'Sec_Ene_Ele_inc_Cur_Solar','solar','#FEC906FF',
                   'Sec_Ene_Ele_H2_FC','fuel cell','orchid',
                   'Sec_Ene_Ele_H2_GT','hydrogen gas turbine','orchid',
                   'Trd_Sec_Ene_Ele','trade','#a3e0ffFF')
flag_elehr2 <- c('Fin_Ene_Ele','Sec_Ene_Ele_Sto_Cha_Gro_PHS','Sec_Ene_Ele_Sto_Cha_Gro_LiB','Sec_Ene_Ele_Own_Use_Ene_Sup_Hyd','Sec_Ene_Ele_Cur')

elehr3 <- tribble(~Variable,~Legend,~Color,
                   'Charge','Charge','#23e893',
                   'Other','Other','grey50',
                   'Discharge','Discharge','#23e893',
                   'Curtailment','Curtailment','#F6CCFFFF',
                   'Wind','Wind','#145db8',
                   'Solar','Solar','#FEC906FF',
                   'Transmission','Transmission','#a3e0ffFF')
flag_elehr3 <- c('Charge','Curtailment')
 
eleyr <- tribble(~Variable,~Legend,~Color,
                  'Sec_Ene_Ele_Trd_Los','transmission loss','#a3e0ffFF',
                  'Sec_Ene_Ele_Cur','curtailment','#F6CCFFFF',
                  'Sec_Ene_Ele_Sto_Los','storage loss','#23e893',
                  'Sec_Ene_Ele_Coa_wo_CCS','coal w/o CCS','#4A4F54FF',
                  'Sec_Ene_Ele_Coa_w_CCS','coal w/ CCS','#8A9197FF',
                  'Sec_Ene_Ele_Oil','oil w/o CCS','#8C655DFF',
                  'Sec_Ene_Ele_Gas_wo_CCS','gas w/o CCS','#8c845b',
                  'Sec_Ene_Ele_Gas_w_CCS','gas w/ CCS','#c2ac69FF',
                  'Sec_Ene_Ele_Nuc','nuclear','#FF9626FF',
                  'Sec_Ene_Ele_Hyd','hydro','#29dde3FF',
                  'Sec_Ene_Ele_Geo','geothermal','#B74F3AFF',
                  'Sec_Ene_Ele_Bio_wo_CCS','biomass w/o CCS','#617f00FF',
                  'Sec_Ene_Ele_Bio_w_CCS','biomass w/ CCS','#a7bf5eFF',
                  'Sec_Ene_Ele_Win_Off','offshore wind','#699bffFF',
                  'Sec_Ene_Ele_Win_Ons','onshore wind','#145db8',
                  'Sec_Ene_Ele_Solar_Dec','solar rooftop','#FFEE75FF',
                  'Sec_Ene_Ele_Solar_Cen','solar utility','#FEC906FF',
                  'Sec_Ene_Ele_H2_FC','fuel cell','orchid',
                  'Sec_Ene_Ele_H2_GT','hydrogen gas turbine','orchid')

flag_eleyr <- c('Sec_Ene_Ele_Trd_Los','Sec_Ene_Ele_Cur','Sec_Ene_Ele_Sto_Los')

eleyr2 <- tribble(~Variable,~Legend,~Color,
                  'Sec_Ene_Ele_Coa','coal','#4A4F54FF',
                  'Sec_Ene_Ele_Oil','oil','#8C655DFF',
                  'Sec_Ene_Ele_Gas','natural gas','#A99F6DFF',
                  'Sec_Ene_Ele_Nuc','nuclear','#FF9626FF',
                  'Sec_Ene_Ele_Hyd','hydro','#29dde3FF',
                  'Sec_Ene_Ele_Geo','geothermal','#B74F3AFF',
                  'Sec_Ene_Ele_Bio','biomass','#AFDD66FF',
                  'Sec_Ene_Ele_Win','wind','#145db8',
                  'Sec_Ene_Ele_Solar','solar','#FEC906FF',
                  'Sec_Ene_Ele_H2_FC','fuel cell','orchid',
                  'Sec_Ene_Ele_H2_GT','hydrogen gas turbine','orchid')

eleyr3 <- tribble(~Variable,~Legend,~Color,
                  'other','other','#a3bdc9',
                  'Sec_Ene_Ele_Coa','coal','#4A4F54FF',
                  'Sec_Ene_Ele_Oil','oil','#8C655DFF',
                  'Sec_Ene_Ele_Gas','natural gas','#A99F6DFF',
                  'Sec_Ene_Ele_Bio','biomass','#AFDD66FF',
                  'Sec_Ene_Ele_Win_Off','offshore wind','#699bffFF',
                  'Sec_Ene_Ele_Win_Ons','onshore wind','#145db8',
                  'Sec_Ene_Ele_Solar_Dec','solar rooftop','#FFEE75FF',
                  'Sec_Ene_Ele_Solar_Cen','solar utility','#FEC906FF',
                  'Sec_Ene_Ele_H2_FC','fuel cell','orchid',
                  'Sec_Ene_Ele_H2_GT','hydrogen gas turbine','orchid')

# ele_inv <- tribble(~Variable,~Legend,~Color,
#                    'Inv_Ele_Trd_Los','transmission loss','#CCEEFFFF',
#                    'Inv_Ele_Cur','curtailment','#F6CCFFFF',
#                    'Inv_Ele_Sto_Los','storage loss','#7fffd4',
#                    'Inv_Ele_Coa_wo_CCS','coal w/o CCS','#4A4F54FF',
#                    'Inv_Ele_Coa_w_CCS','coal w/ CCS','#8A9197FF',
#                    'Inv_Ele_Oil','oil w/o CCS','#8C655DFF',
#                    'Inv_Ele_Gas_wo_CCS','gas w/o CCS','#A99F6DFF',
#                    'Inv_Ele_Gas_w_CCS','gas w/ CCS','#D6BD73FF',
#                    'Inv_Ele_Nuc','nuclear','#FF9626FF',
#                    'Inv_Ele_Hyd','hydro','#90d2f0FF',
#                    'Inv_Ele_Geo','geothermal','#B74F3AFF',
#                    'Inv_Ele_Bio_wo_CCS','biomass w/o CCS','#4E7F00FF',
#                    'Inv_Ele_Bio_w_CCS','biomass w/ CCS','#AFDD66FF',
#                    'Inv_Ele_Win','wind','#197EC0FF',
#                    'Inv_Ele_Solar','solar utility','#FEC906FF')

ele_cap <- tribble(~Variable,~Legend,~Color,
                   'Cap_Ele_Coa_wo_CCS','coal w/o CCS','#4A4F54FF',
                   'Cap_Ele_Coa_w_CCS','coal w/ CCS','#8A9197FF',
                   'Cap_Ele_Oil','oil w/o CCS','#8C655DFF',
                   'Cap_Ele_Gas_wo_CCS','gas w/o CCS','#A99F6DFF',
                   'Cap_Ele_Gas_w_CCS','gas w/ CCS','#D6BD73FF',
                   'Cap_Ele_Nuc','nuclear','#FF9626FF',
                   'Cap_Ele_Hyd','hydro','#90d2f0FF',
                   'Cap_Ele_Geo','geothermal','#B74F3AFF',
                   'Cap_Ele_Bio_wo_CCS','biomass w/o CCS','#4E7F00FF',
                   'Cap_Ele_Bio_w_CCS','biomass w/ CCS','#AFDD66FF',
                   'Cap_Ele_Win_Off','offshore wind','#2192DEFF',
                   'Cap_Ele_Win_Ons','onshore wind','#197EC0FF',
                   'Cap_Ele_Solar_Dec','solar rooftop','#FFEE75FF',
                   'Cap_Ele_Solar_Cen','solar utility','#FEC906FF',
                   'Cap_Ele_H2_GT','hydrogen gas turbine','orchid')

ele_inv <- tribble(~Variable,~Legend,~Color,
                   'Fuel','Fuel','#8C655DFF',
                   'OPEX','OPEX','#4A4F54FF',
                   'CAPEX (other)','CAPEX (other)','#8A9197FF',
                   'CAPEX (fossil w/o CCS)','CAPEX (fossil w/o CCS)','#8c845b',
                   'CAPEX (fossil w/ CCS)','CAPEX (fossil w/ CCS)','#c2ac69FF',
                   'CAPEX (wind)','CAPEX (wind)','#0252b5',
                   'CAPEX (solar)','CAPEX (solar)','#FEC906FF',
                   'CAPEX (battery)','CAPEX (battery)','#32AC9AFF',
                   'CAPEX (hydrogen)','CAPEX (hydrogen)','orchid',
                   'CAPEX (domestic interconnection)','CAPEX (domestic interconnection)','#CCEEFFFF',
                   'CAPEX (international interconnection)','CAPEX (international interconnection)','#83d1f7FF')

ele_inv2 <- tribble(~Variable,~Legend,~Color,
                   'Fuel','Fuel','#8C655DFF',
                   'OPEX','OPEX','#4A4F54FF',
                   'CAPEX (other)','CAPEX (other)','#8A9197FF',
                   'CAPEX (fossil)','CAPEX (fossil)','#c2ac69FF',
                   'CAPEX (solar/wind)','CAPEX (solar/wind)','#FEC906FF',
                   'CAPEX (battery)','CAPEX (battery)','#32AC9AFF',
                   'CAPEX (hydrogen)','CAPEX (hydrogen)','orchid',
                   'CAPEX (domestic interconnection)','CAPEX (domestic transmission)','#83d1f7FF',
                   'CAPEX (international interconnection)','CAPEX (international transmission)','#0252b5')
